# Generated by Django 4.1 on 2024-03-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('NEWS', 'News'), ('FISHING_TRIPS', 'Fishing Trips'), ('TACKLE', 'Tackle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, choices=[('ORVIS', 'Orvis'), ('SAVAGE_GEAR', 'Savage Gear'), ('SHIMANO', 'Shimano'), ('SAGE', 'Sage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
