# Generated by Django 4.1 on 2024-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, choices=[('NEWS', 'News'), ('FISHING_TRIPS', 'Fishing Trips'), ('TACKLE', 'Tackle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('ORVIS', 'Orvis'), ('SAVAGE_GEAR', 'Savage Gear'), ('SHIMANO', 'Shimano'), ('SAGE', 'Sage')], max_length=20, null=True),
        ),
    ]
