# Generated by Django 3.2.21 on 2023-10-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('N', 'NEW'), ('L', 'LOW STOCK'), ('P', 'ON SALE'), ('S', 'SOLD OUT')], max_length=1),
        ),
    ]
